from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
import numpy as np
from collections import Counter



tickets = [
    "my laptop is not turning on",
    "outlook is not opening",
    "vpn not connecting from home",
    "forgot my password please reset",
    "software installation needed",
    "wifi very slow",
    "teams not working",
    "excel file corrupted",
    "printer not working",
    "internet connection dropped",
    "screen went blank",
    "keyboard not responding",
    "cannot access sharepoint",
    "sap showing error",
    "password locked out",
    "remote desktop not working",
    "laptop battery not charging",
    "monitor flickering",
    "mouse not working",
    "cannot install software"
    "wifi dropped",
    "network down",
    "Battery of laptop problem",
    "can't get access to food token",
    "Databricks access required",
    "wifi keeps disconnecting",
    "vpn drops every few minutes",
    "network very slow today",
    "internet not working at desk",
    "cannot reach company server",
    "need access to new system",
    "account locked out",
    "new employee needs login",
    "access denied to folder",
    "reset my password please",
    "my laptop is not turning on", 
    "outlook is not opening", "vpn not connecting from home", "forgot my password please reset", "software installation needed", "wifi very slow", "teams not working", "excel file corrupted", "printer not working", "internet connection dropped", "screen went blank", "keyboard not responding", "cannot access sharepoint", "sap showing error", "password locked out", "remote desktop not working", "laptop battery not charging", "monitor flickering", "mouse not working", "cannot install software", "wifi keeps disconnecting", "vpn drops every few minutes", "network very slow today", "internet not working at desk", "cannot reach company server", "need access to new system", "account locked out", "new employee needs login", "access denied to folder", "reset my password please", "laptop screen cracked", "keyboard keys not working", "printer paper jam", "monitor not displaying", "laptop overheating", "sap login failed", "outlook calendar not syncing", "teams video not working", "sharepoint access denied", "excel formula not working", "vpn certificate expired", "wifi password incorrect", "network drive not accessible", "internet very slow", "remote access not working", "new joinee account setup", "user account disabled", "password expiry notification", "access request for software", "license not available", "laptop touchpad not working", "external mouse not detected", "printer not found in network", "second monitor not detected", "laptop speaker not working", "sap transaction error", "outlook email bouncing", "teams meeting not starting", "onedrive not syncing", "powerpoint not responding", "network cable unplugged", "wifi dropping frequently", "vpn slow connection", "firewall blocking access", "proxy settings issue", "new user account creation", "permission denied on folder", "admin rights needed", "software activation failed", "antivirus license expired", "laptop hinge broken", "desktop computer not starting", "usb port not working", "webcam not detected", "headset not working", "sap data not loading", "email attachment not opening", "teams chat not loading", "browser not opening", "adobe not working", "network printer offline", "internet disconnecting randomly", "vpn not authenticating", "network latency high", "server not reachable", "user locked out of system", "new laptop setup needed", "shared drive access needed", "group permission required", "software upgrade needed", "laptop fan making noise", "computer running very slow", "blue screen error", "laptop charger not working", "ram upgrade needed", "sap performance slow", "outlook not receiving emails", "teams status not updating", "zoom not working", "ms office activation failed","laptop not powering on after shutdown",
"desktop showing blue screen on startup",
"docking station not detecting dual monitors",
"printer not responding in finance department",
"wireless mouse not working",
"keyboard keys typing incorrect characters",
"laptop battery not charging",
"monitor flickering continuously",
"hard drive making clicking noise",
"usb port not recognizing device",
"webcam not detected in teams meeting",
"headset microphone not working",
"laptop overheating during site visit",
"touchpad not functioning",
"external monitor no signal",
"system unit not turning on",
"fan making loud noise in cpu",
"screen cracked on field tablet",
"ethernet port physically damaged",
"power button stuck on laptop",
"printer paper jam error",
"scanner not scanning documents",
"graphics card driver causing display issue",
"beeping sound during boot",
"device randomly shutting down",
"charging cable loose connection",
"camera blurry during video calls",
"bluetooth not detecting devices",
"fingerprint scanner not working",
"projector not displaying image",
"vpn not connecting from home network",
"wifi connected but no internet",
"slow internet speed in office",
"network drive mapping lost",
"lan cable unplugged message",
"ip address conflict detected",
"dns server not responding",
"frequent network disconnections",
"network switch not blinking",
"router not powering on",
"remote desktop not connecting",
"latency high during video conference",
"cannot ping internal server",
"firewall blocking application traffic",
"wifi authentication failed",
"proxy server error",
"intranet site not reachable",
"packet loss observed in branch",
"vpn disconnecting frequently",
"network printer offline",
"outlook not syncing emails",
"sap gui not opening",
"excel macro disabled automatically",
"software installation stuck at halfway",
"application crashing on launch",
"windows update failed repeatedly",
"antivirus showing false alert",
"blue screen after driver update",
"revit software crashing",
"autocad license not activating",
"ms teams screen sharing not working",
"browser not loading internal site",
"onedrive not syncing files",
"power bi dashboard not loading",
"pdf reader not opening files",
"crm tool showing unknown error",
"project management tool not responding",
"email attachments not downloading",
"file explorer crashing",
"sharepoint document not uploading",
"zoom application freezing",
"java runtime error message",
"sql client not connecting to database",
"visual studio not compiling project",
"software asking for repeated activation",
"internal app showing 500 error",
"error code 1603 during install",
"application update failing",
"windows activation error",
"printer driver installation failed",
"macro security warning blocking file",
"browser certificate error",
"database backup job failed",
"system stuck on login screen",
"cannot login to sap hana",
"password expired unable to reset",
"account locked after failed attempts",
"need access to finance shared folder",
"unable to access hr portal",
"access denied to engineering server",
"new employee not added to ad group",
"admin rights required for installation",
"cannot access payroll system",
"azure portal access request",
"jira login not working",
"salesforce account disabled",
"shared mailbox not visible",
"email account disabled",
"vpn access required for vendor",
"sharepoint permission request",
"mfa code not receiving",
"onedrive access restricted",
"unable to join teams channel",
"cannot access intranet homepage",
"database access denied",
"file server permission missing",
"system asking for bitlocker recovery key",
"smart card login not working",
"elevator diagnostic laptop not booting",
"field service app crashing on tablet",
"kone service portal not loading",
"remote monitoring dashboard offline",
"elevator log file not uploading",
"iot gateway offline in building",
"site wifi not reachable",
"device management console error",
"firmware update failed on controller",
"barcode scanner not scanning",
"asset tracking app not syncing",
"time attendance system not accessible",
"vpn error code 809",
"email stuck in outbox",
"printer toner low warning",
"desktop icons missing",
"outlook search not working",
"excel file corrupted",
"word document not opening",
"teams meeting audio echo issue",
"microphone muted automatically",
"camera access blocked by privacy settings",
"software compatibility issue with windows 11",
"hard disk full warning",
"external hard drive not detected",
"shared drive very slow",
"cannot save file to network folder",
"ssl certificate expired warning",
"group policy not applying",
"login script not running",
"device not compliant in intune",
"azure ad sync failure",
"mailbox quota exceeded",
"calendar not syncing",
"public folder missing",
"email rule not working",
"spam filter blocking valid emails",
"network folder asking repeated credentials",
"ftp server not connecting",
"vpn client crashing",
"wifi signal weak in conference room",
"ethernet disconnecting randomly",
"system time not syncing",
"printer printing blank pages",
"scanner driver outdated",
"display resolution incorrect",
"sound not working after update",
"keyboard delay while typing",
"cpu usage high constantly",
"ram usage unusually high",
"system slow after patch update",
"application license expired",
"internal website slow loading",
"file upload failing on portal",
"mobile device not enrolling in mdm",
"lost access to shared calendar",
"cannot attach files in outlook",
"shared printer not visible",
"usb device blocked by policy",
"device encryption failed",
"system restore not completing",
"outlook profile corrupted",
"mailbox not updating",
"onedrive folder duplicated",
"ad account disabled unexpectedly",
"sharepoint site not accessible externally",
"vpn not reconnecting automatically",
"ip phone not registering",
"voip call dropping frequently",
"network cable damaged",
"wifi password changed not updated",
"server not responding",
"cannot access backup server",
"login taking long time",
"file server disk space critical",
"application timeout error",
"internal chat tool not loading",
"mfa app not syncing",
"printer not printing color",
"bluetooth headset disconnecting",
"field tablet battery draining fast",
"network outage in building",
"cannot open company portal",
"remote session freezing",
"device driver missing",
"monitor displaying lines",
"file permission error",
"sharepoint sync conflict",
"database query timing out",
"cannot export report from sap",
"excel pivot table not refreshing",
"teams status not updating",
"browser keeps crashing",
"windows defender disabled automatically",
"software installation requires reboot repeatedly",
"login error invalid credentials",
"ad password not syncing",
"vpn stuck on connecting",
"wifi connected limited access",
"ethernet not detecting network",
"cannot access internal ftp",
"printer spooler service stopped",
"outlook not opening",
"excel crashing on large file",
"revit license server not found",
"autocad file not opening",
"project file missing from server",
"file share quota exceeded",
"usb keyboard not detected",
"system randomly freezing",
"external display flickering",
"audio driver error",
"network share disappeared",
"application service stopped",
"azure vm not starting",
"cloud backup not running",
"mail delivery delayed",
"teams recording not saved",
"camera not working in browser",
"password reset link expired",
"two factor authentication failing",
"shared drive read only access",
"server certificate warning",
"proxy authentication required",
"internal api not responding",
"mobile hotspot not connecting to vpn",
"printer access denied",
"file locked by another user",
"system update pending restart loop",
"wifi captive portal not loading",
"network adapter disabled",
"cloud storage not accessible",
"device serial number not registering",
"ad group membership incorrect",
"email signature not updating",
"calendar invite not sending",
"remote desktop black screen",
"server storage full alert",
"application crashing after login",
"database connection refused",
"file corrupted after download",
"email bounce back error",
"mfa device lost",
"account permission mismatch",
"file synchronization paused",
"vpn gateway unreachable",
"wireless adapter not detected",
"cpu fan error",
"windows login slow",
"sharepoint version history missing",
"cloud app timeout",
"network firewall rule needed",
"printer offline status",
"scan to email not working",
"elevator monitoring app error",
"iot device not reporting data",
"building dashboard offline",
"field engineer cannot upload report",
"service ticketing tool not accessible",
"company portal certificate error",
"remote monitoring latency high",
"backup restore failed",
"ad replication error",
"domain controller unreachable",
"vpn split tunnel not working",
"email phishing alert false positive",
"teams not detecting camera",
"laptop lid sensor not working",
"monitor brightness stuck",
"usb drive read only",
"shared folder access intermittent",
"sql server service stopped",
"outlook calendar missing events",
"wifi dropping during call",
"printer configuration lost",
"vpn login failed credentials",
"device stuck on bios screen",
"application config file missing",
"email search very slow",
"cloud sync pending forever",
"internal portal access denied",
"network performance degradation",
"system log showing disk error",
"mfa push notification delayed",
"desktop background policy not applied",
"printer not installing automatically",
"shared drive not syncing",
"device compliance policy failure",
"server cpu usage high",
"cloud database backup incomplete",
"excel add in disabled",
"word crashing on save",
"vpn dns resolution issue",
"file path too long error",
"email auto reply not working",
"application unable to connect to server",
"wifi adapter driver missing",
"ad account expired",
"shared mailbox permission revoked",
"printer queue stuck",
"system unable to join domain",
"network segmentation issue",
"firewall blocking vpn",
"laptop screen dim automatically",
"audio echo in teams",
"network printer driver outdated",
"browser homepage changed automatically",
"device not visible in network",
"remote desktop credentials error",
"mailbox migration pending",
"database access request",
"field service login failed",
"server backup disk full",
"iot sensor offline",
"company website internal error",
"application crash report generated",
"vpn client outdated version",
"system certificate trust error",
"wifi mac address blocked",
"monitor not waking from sleep",
"ad password complexity error",
"email attachments blocked",
"cloud portal not reachable",
"printer duplex not working",
"network drive slow response",
"shared folder missing files",
"file rename permission denied",
"server reboot required",
"mobile email not syncing",
"mfa code invalid",
"software patch failed",
"windows defender update failed",
"excel formula not calculating",
"project server not accessible",
"database login failed",
"vpn authentication timeout",
"wifi interference issue",
"ethernet speed limited to 100mbps",
"laptop stuck in airplane mode",
"printer driver conflict",
"scanner not detected",
"application dependency missing",
"file server not mapped",
"system restore point failed",
"email forwarding not working",
"sharepoint external sharing blocked",
"server time incorrect",
"network outage reported",
"cloud service unavailable",
"password change not reflecting",
"device stuck on update screen",
"remote support tool not launching",
"file cannot be deleted access denied",
"vpn profile missing",
"network cable unplugged error",
"printer not scanning to folder",
"application license server down",
"database replication issue",
"wifi router overheating",
"system not detecting second monitor",
"email delay in sending",
"mfa backup code not working",
"sharepoint folder sync error",
"server disk read error",
"ad group policy conflict",
"browser popups appearing",
"printer ink smudging",
"network adapter driver outdated",
"cloud login session expired",
"internal messaging app not sending messages",
"server memory leak suspected",
"vpn reconnect loop",
"file share permission escalation request",
"windows activation key invalid",
"teams chat history missing",
"wifi auto connect not working",
"database performance slow",
"device encryption recovery needed",
"email rule deleting messages unexpectedly",
"application cache corruption",
"printer port not configured",
"network broadcast storm suspected",
"cloud sync error conflict",
"remote desktop certificate warning",
"laptop hinge loose",
"shared calendar permission removed",
"server audit log full",
"vpn client not updating",
"file server unreachable",
"wifi network hidden",
"system crash dump generated",
"email cannot connect to exchange",
"application service dependency failed",
"usb device policy restriction",
"printer cannot connect to wifi",
"azure ad conditional access blocking login",
"network ip conflict recurring",
"cloud storage quota exceeded",
"outlook stuck on loading profile",
"database table locked",
"teams meeting invite missing link",
"laptop keyboard backlight not working",
"system bios update failed",
"sharepoint document version conflict",
"vpn throughput very slow",
"file access audit required",
"printer color calibration issue",
"wifi channel congestion",
"server patch installation pending",
"email smtp authentication error",
"cloud application permission denied",
"network security scan detected vulnerability",
"device compliance check failed",
"remote desktop gateway error",
"application log file growing rapidly",
"shared drive folder renamed accidentally",
"server raid degraded warning",
"vpn certificate expired",
"email dkim verification failed",
"database disk latency high",
"wifi repeater not working",
"laptop camera privacy shutter stuck",
"system unable to detect hard disk",
"printer offline after power outage",
"cloud app login redirect loop",
"network qos configuration issue",
"sharepoint recycle bin empty unexpectedly",
"vpn user limit reached",
"email exchange service stopped",
"file server migration issue",
"application api key invalid",
"wifi roaming issue between access points",
"server power supply failure",
"remote login session terminated",
"cloud backup encryption error",
"network monitoring alert triggered",
"printer authentication required",
"database schema mismatch error",
"Hardware", "Hardware", "Hardware", "Hardware", "Hardware", "Hardware", "Hardware", "Hardware", "Hardware", "Hardware", "Hardware", "Hardware", "Hardware", "Hardware", "Hardware", "Hardware", "Hardware", "Hardware", "Hardware", "Hardware", "Hardware", "Hardware", "Hardware", "Hardware", "Hardware", "Hardware", "Hardware","Hardware","Hardware","Hardware","Hardware","Hardware","Hardware","Hardware","Hardware","Hardware","Hardware","Hardware","Hardware","Hardware","Hardware",
"Software","Software","Software","Software","Software","Software","Software","Software","Software","Software","Software","Software","Software","Software",
"Network","Network","Network","Network","Network","Network","Network","Network","Network","Network","Network","Network","Network",
"Access","Access","Access","Access","Access","Access","Access","Access","Access","Access","Access","Access","Access"

"vpn split tunnel misconfiguration",
"email alias not created",
"system clock out of sync",
"sharepoint search not indexing",
"wifi adapter power management issue",
"server event log critical error",
"application not compatible with latest patch",
"network firewall firmware outdated",
"cloud instance not reachable",
"printer default settings changed",
"database backup schedule missing",
"vpn gateway high cpu usage",
"email archive not accessible",
"shared drive permission inheritance broken",
"system login audit failure",
"wifi captive portal timeout",
"server dns misconfiguration",
"application ui not loading properly",
"network bandwidth saturation detected",
"cloud sync service stopped",
"printer secure print not releasing",
"database transaction log full",
"vpn authentication server down",
"email spam quarantine inaccessible",
"sharepoint workflow not triggering",
"system disk cleanup required",
"wifi authentication loop",
"server ssl handshake error",
"application session timeout too short",
"network intrusion detection alert",
"cloud api rate limit exceeded",
"printer ip address changed",
"database deadlock detected",
"vpn connection blocked by isp",
"email auto archive not running",
"shared folder accidentally deleted",
"system driver signature error",
"wifi access point offline",
"server virtualization host not responding",
"application report export failing",
"network configuration reset needed",
"cloud storage sync very slow",
"printer unable to print pdf",
"database index corruption",
"vpn tunnel dropping intermittently",
"email attachment size limit exceeded",
"sharepoint site collection quota reached",
"system memory diagnostic error",
"wifi security protocol mismatch",
"server cluster node down",
"application plugin not supported",
"network load balancer misrouting traffic",
"cloud environment variable missing",
"printer unable to authenticate user",
"database user role misconfigured",
"vpn client profile corrupted",
"email mailbox delegation not working",
"shared drive mount point error",
"system temperature warning alert",
"wifi password expired",
"server backup verification failed",
"application installer checksum mismatch",
"network arp table overflow",
"cloud resource access key expired",
"printer firmware update required",
"database service restart required",
"vpn route not added correctly",
"email sync folder hierarchy mismatch",
"sharepoint permissions inheritance broken",
"system bitlocker key not accepted","laptop display broken",
"computer not booting",
"desktop fan not working",
"ram not detected",
"hard disk making noise",
"laptop power button stuck",
"keyboard backlight not working",
"touchpad not responding",
"laptop port damaged",
"usb hub not working",
"graphics card error",
"laptop battery swollen",
"computer beeping on startup",
"processor overheating",
"laptop screen lines appearing",
"computer freezing randomly",
"laptop lid not closing",
"external hard disk not detected",
"computer restarting automatically",
"laptop charger port broken",
"desktop monitor no signal",
"keyboard water damaged",
"printer cartridge empty",
"scanner not working",
"laptop numpad not working",
"docking station not working",
"laptop audio jack broken"

]

labels = [
    "Hardware", "Software", "Network", "Access", "Software",
    "Network", "Software", "Software", "Hardware", "Network",
    "Hardware", "Hardware", "Software", "Software", "Access",
    "Network", "Hardware", "Hardware", "Hardware", "Software",
    "Network", "Network", "Hardware", "Software", "Access","Network",
    "Network","Network","Network","Network","Access","Access","Access","Access",
    "Hardware", "Software", "Network", "Access", "Software", "Network", "Software", "Software", "Hardware", "Network", "Hardware", "Hardware", "Software", "Software", "Access", "Network", "Hardware", "Hardware", "Hardware", "Software", "Network", "Network", "Network", "Network", "Network", "Access", "Access", "Access", "Access", "Access", "Hardware", "Hardware", "Hardware", "Hardware", "Hardware", "Software", "Software", "Software", "Software", "Software", "Network", "Network", "Network", "Network", "Network", "Access", "Access", "Access", "Access", "Access", "Hardware", "Hardware", "Hardware", "Hardware", "Hardware", "Software", "Software", "Software", "Software", "Software", "Network", "Network", "Network", "Network", "Network", "Access", "Access", "Access", "Access", "Access", "Hardware", "Hardware", "Hardware", "Hardware", "Hardware", "Software", "Software", "Software", "Software", "Software", "Network", "Network", "Network", "Network", "Network", "Access", "Access", "Access", "Access", "Access", "Hardware", "Hardware", "Hardware", "Hardware", "Hardware", "Software", "Software", "Software", "Software", "Software","Hardware","Hardware","Hardware","Hardware","Hardware","Hardware","Hardware","Hardware","Hardware","Hardware",
"Hardware","Hardware","Hardware","Hardware","Hardware","Hardware","Hardware","Hardware","Hardware","Hardware",
"Hardware","Hardware","Software","Hardware","Hardware","Hardware","Hardware","Hardware","Hardware","Hardware",
"Network","Network","Network","Network","Network","Network","Network","Network","Network","Hardware",
"Network","Network","Network","Network","Network","Network","Network","Network","Network","Network",
"Software","Software","Software","Software","Software","Software","Software","Software","Software","Software",
"Software","Software","Software","Software","Software","Software","Software","Software","Software","Software",
"Software","Software","Software","Software","Software","Software","Software","Software","Software","Software",
"Access","Access","Access","Access","Access","Access","Access","Access","Access","Access",
"Access","Access","Access","Access","Access","Access","Access","Access","Access","Access",
"Access","Access","Access","Access","Access","Access","Access","Access","Access","Access",
"Hardware","Software","Software","Network","Software","Network","Software","Hardware","Software","Software",
"Network","Software","Software","Software","Software","Network","Software","Hardware","Software","Hardware",
"Software","Hardware","Software","Software","Software","Software","Software","Software","Software","Software",
"Software","Network","Software","Access","Software","Network","Software","Software","Software","Access",
"Software","Access","Network","Network","Network","Hardware","Software","Access","Access","Access",
"Network","Network","Network","Software","Software","Software","Access","Access","Access","Network",
"Network","Software","Access","Network","Software","Software","Network","Hardware","Software","Software",
"Access","Software","Network","Hardware","Access","Network","Network","Software","Software","Software",
"Hardware","Software","Network","Software","Software","Software","Software","Access","Access","Network",
"Network","Hardware","Software","Access","Network","Network","Hardware","Access","Software","Network",
"Software","Access","Access","Network","Hardware","Software","Software","Software","Network","Access",
"Hardware","Software","Software","Software","Access","Software","Software","Access","Network","Hardware",
"Software","Network","Hardware","Access","Network","Software","Network","Access","Software","Hardware",
"Network","Software","Access","Network","Hardware","Software","Access","Software","Network","Access",
"Software","Network","Hardware","Software","Network","Access","Software","Network","Access","Software",
"Hardware","Access","Software","Network","Hardware","Access","Network","Software","Network","Software",
"Access","Software","Network","Hardware","Software","Network","Access","Software","Hardware","Access",
"Software","Network","Access","Software","Hardware","Software","Network","Access","Network","Software",
"Hardware","Software","Access","Network","Software","Hardware","Access","Software","Network","Hardware",
"Software","Network","Access","Software","Network","Access","Hardware","Software","Network","Access",
"Software","Network","Hardware","Access","Software","Network","Access","Software","Network","Access",
"Software","Network","Hardware","Software","Network","Access","Software","Network","Access","Software",
"Hardware","Software","Network","Access","Software","Network","Hardware","Access","Software","Network",
"Access","Software","Network","Hardware","Software","Access","Network","Software","Network","Access",
"Software","Network","Hardware","Software","Network","Access","Software","Network","Access","Software",
"Hardware","Software","Network","Access","Software","Network","Hardware","Access","Software","Network",
"Access","Software","Network","Hardware","Software","Access","Network","Software","Network","Access",
"Software","Network","Hardware","Software","Network","Access","Software","Network","Access","Software",
"Hardware","Software","Network","Access","Software","Network","Hardware","Access","Software","Network",
"Access","Software","Network","Hardware","Software","Access","Network","Software","Network","Access",
"Software","Network","Hardware","Software","Network","Access","Software","Network","Access","Software",
"Hardware","Software","Network","Access","Software","Network","Hardware","Access","Software","Network",
"Access","Software","Network","Hardware","Software","Access","Network","Software","Network","Access",
"Software","Network","Hardware","Software","Network","Access","Software","Network","Access","Software",
"Hardware","Software","Network","Access","Software","Network","Hardware","Access","Software","Network",
"Access","Software","Network","Hardware","Software","Access","Network","Software","Network","Access",
"Software","Network","Hardware","Software","Network","Access","Software","Network","Access","Software","Hardware","Hardware","Hardware","Hardware","Hardware","Hardware","Hardware","Hardware","Hardware",
"Software","Software","Software","Software","Software","Software","Software","Software","Software",
"Network","Network","Network","Network","Network","Network","Network","Network","Network",
"Access","Access","Access","Access","Access","Access","Access","Access","Access","Hardware", "Hardware", "Hardware", "Hardware", "Hardware", "Hardware", "Hardware", "Hardware", "Hardware", "Hardware", "Hardware", "Hardware", "Hardware", "Hardware", "Hardware", "Hardware", "Hardware", "Hardware", "Hardware", "Hardware", "Hardware", "Hardware", "Hardware", "Hardware", "Hardware", "Hardware", "Hardware", "Network", "Network", "Network", "Network", "Network", "Network", "Network", "Network", "Network", "Network", "Network", "Network", "Network", "Network", "Network", "Network", "Network", "Network", "Network", "Network", "Access", "Access", "Access", "Access", "Access", "Access", "Access", "Access", "Access", "Access", "Access", "Access", "Access", "Access", "Access", "Access", "Access", "Access", "Access", "Access", "Software", "Software", "Software", "Software", "Software", "Software", "Software", "Software", "Software", "Software", "Software", "Software", "Software", "Software", "Software", "Software", "Software", "Software", "Software", "Software", "Software", "Software", "Software", "Software", "Software", "Software", "Software", "Hardware", "Hardware", "Hardware", "Hardware", "Hardware", "Hardware", "Hardware", "Hardware", "Hardware", "Hardware", "Hardware", "Hardware"



]
min_count = min(len(tickets), len(labels))
tickets = tickets[:min_count]
labels = labels[:min_count]

print(f"Tickets: {len(tickets)}")
print(f"Labels: {len(labels)}")

model = Pipeline([
    ('tfidf', TfidfVectorizer()),
    ('classifier', MultinomialNB()),
])

model.fit(tickets, labels)

print("Model Trained Successfully!")
print(f"Trained on {len(tickets)} tickets!")

# ================================
# TEST YOUR TRAINED MODEL
# ================================

def predict(ticket):
    prediction = model.predict([ticket])
    confidence = model.predict_proba([ticket])
    max_confidence = round(max(confidence[0]) * 100, 2)
    return prediction[0], max_confidence

# Test with new tickets
test_tickets = [
    "my screen is flickering",
    "cannot connect to wifi",
    "need password reset urgently",
    "sap is crashing",
    "laptop fell and not working",
]

print("\n--- TESTING YOUR ML MODEL ---")
for ticket in test_tickets:
    category, confidence = predict(ticket)
    print(f"Ticket: {ticket}")
    print(f"Category: {category} | Confidence: {confidence}%")
    print("---")


##  Every Line Explained:
def predict(ticket):
    prediction = model.predict([ticket])
    confidence = model.predict_proba([ticket])
    max_confidence = round(max(confidence[0]) * 100, 2)
    return prediction[0], max_confidence

test_tickets = [
    "my screen is flickering",
    "cannot connect to wifi",
    "need password reset urgently",
    "sap is crashing",
    "laptop fell and not working",
]

print("\n--- TESTING YOUR ML MODEL ---")
for ticket in test_tickets:
    category, confidence = predict(ticket)
    print(f"Ticket: {ticket}")
    print(f"Category: {category} | Confidence: {confidence}%")
    print("---")
    print(f"Tickets: {len(tickets)}")
print(f"Labels: {len(labels)}")
print(f"Difference: {len(tickets) - len(labels)}")
print("\n--- DATA QUALITY CHECK ---")
label_counts = Counter(labels)
for label, count in label_counts.items():
    print(f"{label}: {count} tickets")
    print(f"Tickets: {len(tickets)}")
print(f"Labels: {len(labels)}")
print(f"Difference: {len(tickets) - len(labels)}")



   